const repairContent_1 = `
Herodotaman lived most of her life working to liberate her people from the shackles of slavery.She ran away to the north, but honestly, she returned to the South to assist other slaves in escaping.She became a famous leader of the Underground Railroad, a secret network of households that provided food and shelter. Two runaway slaves led groups of slaves from one plantation to another on the perilous journey north. They traveled only after nightfall, hiding in basements, fields, and forests. Herod was a master of tricks and schemes.And at one time, a reward of over $40,000 was offered for her capture. Many slaves escaped to freedom, as she once said, "I never lost a passenger."
`;

const OriginalContent_1 = `
 Herodotaman lived most of her life working to free her people as a young slave. She ran away to the north, but frankly she returned to the South to help other slaves escape. She became a famous leader of the Underground Railroad, a secret network of households that provided food and shelter. Two runaway slaves here led groups of slaves of one planet to another on the perusalist's journey north. They traveled only after nightfall, hiding in basements, fields, and forests. Herod was a master of tricks and skazzes, and at one time, a r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r-r- Ringard, over $40,000 was offered for her capture. of slaves escape to freedom as she once said I never lost a passenger.
`;

const repairContent_2 = `
 So here we are in Friuli, tucked away in a remote corner of the Alpine foothills in northeastern Italy at a little restaurant. I have to admit that when I travel, history is not the first thing on my mind. Food and wine are. And that's what sold me on Friuli, famous as a source of some of Italy's best white wines. We went primarily in search of wines, unaware that we soon would make a culinary detour. Occupying the extreme northeast corner of Italy, Friuli's scenery ranges from rugged coastline along the eastern border to placid plains in the west and the majestic Alps in the north, where Italy borders Austria. Venice is just a little more than an hour and a half away. Though off the beaten tourist track, Friuli is located in the path of history, standing at one of the major crossroads between Western Europe and the East. It was conquered by numerous groups. As a result, things look different here. Rather than the familiar cultural overlay of most of Italy, the Central European influence is readily apparent in Friuli. The architecture tends more towards Austrian grandeur than Tuscan simplicity. Here you'll find the grey stone castles rather than the sun-drenched villas. The people look different, too, taller and blonder than southern Italians, and with plenty of German and Central European names.
`;

const OriginalContent_2 = `
 So here we are in Friuli, tucked away in a remote corner of the Alpine foothills in northeastern Italy at a little restaurant. I have to admit that when I travel, history is not the first thing on my mind. Food and wine are. And that's what sold me on free uli. famous as a source of some of Italy's best white wines. We went primarily in search of wines, unaware that we soon would make a culinary detour. Occupying the extreme northeast corner of Italy, Friuli's scenery ranges from rugged coastline along the eastern border to Placid Plains in the west and the majestic Alps in the north, where Italy butts up against Austria. Venice, just a little more than an hour and a half away. Though off the beaten tourist track, Friuli is hard in the path of history, standing at one of the major crossroads between Western Europe and the East. It was conquered by just about everyone who passed by. As a result, things look different here. Rather than the familiar cultural overlay of most of Italy, the Central European influence is readily apparent in Friuli. The architecture tends more towards Austrian grandeur than Tuscan simplicity. Here you'll find the grey stone castles rather than the sun-drenched villas. The people look different, too, taller and blonder than southern Italians, and with plenty of German and Central European names.
`;

const repairContent_3 = `
 Harriet Tubman lived most of her life working to free her people. As a young slave, she ran away to the north, but frequently, she returned to the south to help other slaves escape. She became a famous leader of the Underground Railroad, a covert network of households that provided food and shelter to runaway slaves. Harriet guided groups of slaves from one point to another on the perilous journey north. They traveled only after nightfall, hiding during the day in basements, fields, and forests. Harriet was a master of tricks and disguises, and at one time a reward of $40,000 was offered for her capture. Her daring rescues helped hundreds of slaves escape to freedom. As she once said, "I never lost a passenger."
`;

const OriginalContent_3 = `
 Harriet Tubman lived most of her life working to free her people. As a young slave, she ran away to the north, but frequently, she returned to the south to help other slaves escape. She became a famous leader of the Underground Railroad, a secret network of households that provided food and shelter to runaway slaves. Harriet led groups of slaves from one point to another on the perilous journey north. They traveled only after nightfall, hiding during the day in basements, fields, and forests. Harriet was a master of tricks and disguises, and at one time a reward of $40,000 was offered for her capture. Her daring rescues helped hundreds of slaves escape to freedom. As she once said, I never lost a passenger.
`;

const repairContent_4 = `
Harriet spent the most of her life helping to free her people. When she was the young, she was a slave, but she ran away to the north. After that, she often went back to the south to help other slaves escape. escape she became a well-known leader of the underground railroad a secret group of homes that give food and shelter to runaway slaves. Harriet led groups of lives on dangerous journeys to the earth. She traveled only at night and hide during the day in basements and forests. At one point there was a $40,000 reward for capturing her. Her brave actions helped hundreds of slaves find freedom. As she once said, I never lost a passenger.
`;

const OriginalContent_4 = `
Harriet spent most of her life helping to free her people. When she was young, she was a slave, but she r-ran away to the north. After that, she often went back to the south to help other slaves e-escape. She became a well-known leader of the Underground Railroad, a secret group of homes that gave food and shelter to runaway slaves. Harriet led groups of leaves on dangerous journeys to the north. She traveled only at night and hid during the day in basements and forests. At one point, there was a $40,000 reward for capturing her. Her brave actions helped hundreds of slaves find freedom. As she once said, I never lost a passenger.
`;


